
services:
  - type: web
    name: doomz-karma-service
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: BROADCASTER_LOGIN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PUBLIC_URL
        sync: false
